import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Seo } from "@/components/Seo";
import { articleDescription, publicUrl, SITE_NAME } from "@/lib/seo";
import { castVote, createComment, fetchComments, fetchPublishedPost, fetchVoteSummary, useSupabaseQuery } from "@/lib/supabase";
import { ArrowBigDown, ArrowBigUp, ArrowLeft, CalendarDays, MessageSquare, Send } from "lucide-react";
import { useState } from "react";
import { Streamdown } from "streamdown";
import { Link, useLocation, useRoute } from "wouter";

function readableDate(value: Date | string | null) { return new Date(value ?? Date.now()).toLocaleDateString(undefined, { day: "numeric", month: "long", year: "numeric" }); }
function VoteBox({ postId }: { postId: string }) { const { isAuthenticated } = useAuth(); const [, setLocation] = useLocation(); const summary = useSupabaseQuery(() => fetchVoteSummary(postId), [postId]); const [isVoting, setIsVoting] = useState(false); const cast = async (value: 1 | -1) => { if (!isAuthenticated) { setLocation("/"); return; } setIsVoting(true); try { await castVote(postId, value); await summary.refetch(); } finally { setIsVoting(false); } }; return <div className="vote-box" aria-label="Post vote"><button disabled={isVoting} onClick={() => void cast(1)} aria-label="Like post"><ArrowBigUp size={22} /></button><strong>{summary.data?.score ?? 0}</strong><button disabled={isVoting} onClick={() => void cast(-1)} aria-label="Dislike post"><ArrowBigDown size={22} /></button><span>{summary.data?.total ?? 0} votes</span></div>; }
function Discussion({ postId }: { postId: string }) { const { isAuthenticated, user } = useAuth(); const [, setLocation] = useLocation(); const [body, setBody] = useState(""); const [isPosting, setIsPosting] = useState(false); const [postError, setPostError] = useState<string>(); const comments = useSupabaseQuery(() => fetchComments(postId), [postId]); const submit = async () => { setIsPosting(true); setPostError(undefined); try { await createComment(postId, body.trim()); setBody(""); await comments.refetch(); } catch (error) { setPostError(error instanceof Error ? error.message : "Your comment could not be posted."); } finally { setIsPosting(false); } }; return <section className="discussion" id="discussion"><div className="section-kicker"><MessageSquare size={15} /> Comments</div><h2>Comments</h2><p className="discussion__intro">Stay on topic. Add a source if you can, and be clear when you are sharing an opinion.</p>{isAuthenticated ? <div className="comment-form"><Textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder={`Write a comment as ${user?.name ?? "a reader"}…`} /><Button disabled={body.trim().length < 2 || isPosting} onClick={() => void submit()}><Send size={15} /> {isPosting ? "Posting…" : "Post comment"}</Button>{postError && <p className="form-error">{postError}</p>}</div> : <div className="login-prompt"><p>Sign in to comment or vote on this post.</p><Button variant="outline" onClick={() => setLocation("/")}>Go to posts</Button></div>}<div className="comment-list">{comments.isLoading && <p className="muted-copy">Loading comments…</p>}{comments.error && <div className="query-error"><span>Comments could not load.</span><Button size="sm" variant="outline" onClick={() => void comments.refetch()}>Try again</Button></div>}{!comments.isLoading && !comments.error && !comments.data?.length && <p className="muted-copy">No comments yet. Start the conversation.</p>}{comments.data?.map((comment) => <article className="comment" key={comment.id}><div className="comment__avatar">{(comment.authorName || "R").slice(0, 1).toUpperCase()}</div><div><header><strong>{comment.authorName || "Reader"}</strong><time>{readableDate(comment.createdAt)}</time></header><p>{comment.body}</p></div></article>)}</div></section>; }
export default function ArticlePage() { const [, params] = useRoute("/article/:slug"); const slug = params?.slug ?? ""; const article = useSupabaseQuery(() => fetchPublishedPost(slug), [slug]); const post = article.data; if (article.isLoading) return <main className="reading-shell"><p className="muted-copy">Loading post…</p></main>; if (article.error || !post) return <main className="reading-shell empty-state"><h1>Post not found.</h1><p>It may have been removed, unpublished, or the link may be wrong.</p><Link href="/" className="text-link">Back to posts</Link></main>; const path = `/article/${post.slug}`; const description = articleDescription(post.body); const publishedDate = new Date(post.publishedAt ?? post.createdAt).toISOString(); const structuredData = { "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description, datePublished: publishedDate, dateModified: new Date(post.updatedAt).toISOString(), mainEntityOfPage: publicUrl(path), author: { "@type": "Person", name: post.authorName || "Chronicle staff" }, publisher: { "@type": "Organization", name: SITE_NAME }, keywords: post.tags.join(", ") }; return <><Seo title={`${post.title} | ${SITE_NAME}`} description={description} path={path} structuredData={structuredData} /><main className="reading-shell"><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to posts</Link><article className="article-view"><header className="article-view__header"><div className="article-view__topline"><span>{post.category}</span><span className="eyebrow-rule" /><time><CalendarDays size={14} />{readableDate(post.publishedAt ?? post.createdAt)}</time></div><h1>{post.title}</h1><div className="article-view__byline"><span>By <strong>{post.authorName || "Chronicle staff"}</strong></span><span className="byline-dot">•</span><span>Published post</span></div>{post.tags.length > 0 && <div className="tag-row tag-row--article">{post.tags.map((tag) => <span key={tag} className="tag">{tag}</span>)}</div>}</header>{post.coverImageUrl && <img className="article-cover" src={post.coverImageUrl} alt="Article cover" />}<div className="article-reading-grid"><aside><VoteBox postId={post.id} /></aside><div className="article-prose"><Streamdown>{post.body}</Streamdown></div></div></article><Discussion postId={post.id} /></main></>; }
